#!/bin/bash
# python3 -m venv .venv
# source ./.venv/bin/activate
# pip3 install -r requirements.txt
#
# conan profile detect
# conan install . --build=missing
# conan build . --build=missing -s build_type=Debug
conan build . --build=missing

pip install .

pytest "tests/test_convert.py"
pytest "tests/test_transform.py"
pytest "tests/test_mixer.py"
python "tests/test_beat.py"
